mqtt:
  broker: "iot.taginator.cn"
  port: 39683
  topic1: "nssol/rtb/sensor1"
  topic2: "nssol/rtb/sensor2"

http:
  endpoint: "http://iot.taginator.cn:39699/rtb/result"

camera:
  ip1: "192.168.1.65"
  rtsp_url1: "rtsp://camera65:nssol2023@nat.reimu.site:39665/ch1/main/av_stream"
  ip2: "192.168.1.67"
  rtsp_url2: "rtsp://camera65:nssol2023@nat.reimu.site:39667/ch1/main/av_stream"

team:
  name: "线条小狗"

image:
  width: 640
  height: 480

textSize: 20

pose:
  protoFile: "./checkpoints/pose_deploy_linevec.prototxt"
  weightsFile: "./checkpoints/pose_iter_440000.caffemodel"

yunet:
  yunetFile: './checkpoints/yunet.onnx'
  score_threshold: 0.6
  nms_threshold: 0.3
  sfaceFile: './checkpoints/sface.onnx'
  modelFile: './checkpoints/largeFaceRecognize4.pkl'
